# Generated by Django 3.0.7 on 2020-06-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identificador', models.CharField(max_length=500)),
                ('OC', models.CharField(max_length=500)),
                ('FechaApertura', models.DateTimeField(auto_now=True)),
                ('Cantidad', models.IntegerField()),
                ('PrecioLista', models.IntegerField()),
                ('PrecioFacturado', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
    ]
