# Generated by Django 3.0.7 on 2020-06-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='FechaApertura',
            field=models.DateTimeField(),
        ),
    ]
