# Generated by Django 3.0.7 on 2020-06-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_auto_20200607_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='OC',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
