# Generated by Django 3.0.7 on 2020-06-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0007_auto_20200613_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Segment', models.CharField(blank=True, max_length=500, null=True)),
                ('GastoOT', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Cliente', models.IntegerField(blank=True, null=True)),
                ('PorCliente', models.FloatField(blank=True, null=True)),
                ('MontoOts', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('PorMontoOts', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Descuento', models.FloatField(blank=True, null=True)),
                ('VIPx', models.FloatField(blank=True, null=True)),
                ('VIP', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Frecuencia', models.FloatField(blank=True, null=True)),
                ('OtCliente', models.FloatField(blank=True, null=True)),
                ('Activo', models.IntegerField(blank=True, null=True)),
                ('Alerta', models.IntegerField(blank=True, null=True)),
                ('Desertor', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
