# Generated by Django 3.0.7 on 2020-06-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0008_dataanalysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataanalysis',
            options={'verbose_name_plural': 'DataAnalysis'},
        ),
    ]
