# Generated by Django 3.0.7 on 2020-08-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0009_auto_20200622_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataanalysis',
            name='OtCliente',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
