# Generated by Django 3.0.7 on 2020-08-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0011_auto_20200827_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataanalysis',
            name='GastoOT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='MontoOts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='PorOts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='VIP',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
