# Generated by Django 3.0.7 on 2020-08-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0013_dataanalysisres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataAnalysisRes',
        ),
    ]
